'use client';

import Link from 'next/link';
import { T } from '@/lib/theme';

export default function TermsPage() {
  return (
    <div style={{ minHeight: '100vh', background: T.bg, color: T.text, padding: '24px' }}>
      <div style={{ maxWidth: 700, margin: '0 auto' }}>
        <Link href="/" style={{ fontSize: 12, color: T.teal, textDecoration: 'none', marginBottom: 20, display: 'block' }}>&larr; Back to AI Planner</Link>
        <h1 style={{ fontSize: 28, fontWeight: 700, marginBottom: 8, background: `linear-gradient(135deg,${T.teal},${T.blue})`, WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>Terms of Service</h1>
        <p style={{ fontSize: 12, color: T.textMuted, marginBottom: 32 }}>Last updated: April 2026</p>

        {[
          { t: 'Acceptance', b: 'By using AI Planner, you agree to these terms. If you do not agree, do not use the service.' },
          { t: 'Service Description', b: 'AI Planner is a personal productivity tool that integrates with Google Calendar, Gmail, and RMIT Canvas to provide AI-generated briefings, to-do lists, study materials, and scheduling suggestions. AI features are powered by the Anthropic Claude API.' },
          { t: 'Account', b: 'You sign in using your Google account. You are responsible for maintaining the security of your Google account. You must not share your Canvas API token with others or use the service to access data you are not authorised to access.' },
          { t: 'AI-Generated Content', b: 'Study materials, briefings, scheduling suggestions, and other AI outputs are generated by machine learning models and may contain errors. You should verify important information (exam dates, assignment deadlines) against official university sources. AI Planner is a planning aid, not a replacement for official university communications.' },
          { t: 'Data Usage', b: 'Your data is processed as described in our Privacy Policy. By using the service, you consent to your calendar events, emails, and Canvas data being sent to the Anthropic Claude API for processing.' },
          { t: 'Acceptable Use', b: 'You agree not to: use the service for any unlawful purpose, attempt to access other users\u2019 data, reverse-engineer or attack the service, or use automated scripts to abuse API rate limits.' },
          { t: 'Availability', b: 'AI Planner is provided as-is. We do not guarantee 100% uptime. AI features depend on third-party APIs (Google, Anthropic, Canvas) that may experience outages. During outages, the app falls back to cached data where available.' },
          { t: 'Termination', b: 'You can delete your account at any time. We may suspend or terminate accounts that violate these terms.' },
          { t: 'Limitation of Liability', b: 'AI Planner is provided without warranty. We are not liable for missed deadlines, incorrect AI suggestions, or any academic consequences resulting from reliance on the service.' },
          { t: 'Changes', b: 'We may update these terms. Continued use after changes constitutes acceptance.' },
        ].map((s) => (
          <div key={s.t} style={{ marginBottom: 24 }}>
            <h2 style={{ fontSize: 16, fontWeight: 600, color: T.text, marginBottom: 8 }}>{s.t}</h2>
            <p style={{ fontSize: 13, color: T.textSoft, lineHeight: 1.8, fontWeight: 300 }}>{s.b}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
