'use client';

import Link from 'next/link';
import { T } from '@/lib/theme';

export default function TermsPage() {
  return (
    <div style={{ minHeight: '100vh', background: T.bg, color: T.text, padding: '24px' }}>
      <div style={{ maxWidth: 700, margin: '0 auto' }}>
        <Link href="/" style={{ fontSize: 12, color: T.teal, textDecoration: 'none', marginBottom: 20, display: 'block' }}>&larr; Back to AI Planner</Link>
        <h1 style={{ fontSize: 28, fontWeight: 700, marginBottom: 8, background: `linear-gradient(135deg,${T.teal},${T.blue})`, WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>Terms of Service</h1>
        <p style={{ fontSize: 12, color: T.textMuted, marginBottom: 32 }}>Last updated: April 2026</p>

        {[
          { t: 'Acceptance', b: 'By using AI Planner, you agree to these terms. If you do not agree, do not use the service.' },
          { t: 'Service Description', b: 'AI Planner is a personal productivity tool that integrates with Google Calendar and optionally RMIT Canvas to mirror your schedule, surface deadlines, and — where you opt in — generate AI briefings, nudges, and schedule suggestions. AI features are powered by the Anthropic Claude API.' },
          { t: 'Account', b: 'You sign in using Google OAuth or email+password. You are responsible for maintaining the security of your account credentials. You must not share your Canvas API token with others or use the service to access data you are not authorised to access.' },
          { t: 'Pricing & Trial', b: 'New accounts receive a 7-day free trial with full access. After the trial, continued use requires a paid subscription (currently US$6.90/month, billed monthly by Stripe). Prices may change with 30 days\u2019 notice. Cancel anytime from Settings or the Stripe Customer Portal — access remains until the end of the paid period.' },
          { t: 'Refunds', b: 'Because the service is delivered digitally and the 7-day trial gives you full access before payment, all sales are final and we do not offer pro-rata refunds for partial months. If you experience a billing error or extended outage, contact us and we will resolve it in good faith.' },
          { t: 'AI-Generated Content', b: 'Briefings, nudges, scheduling suggestions, and other AI outputs are generated by machine-learning models and may contain errors. You should verify important information (exam dates, assignment deadlines) against official sources. AI Planner is a planning aid, not a replacement for official university communications.' },
          { t: 'Data Usage', b: 'Your data is processed as described in our Privacy Policy. By using the service, you consent to relevant slices of your calendar and Canvas data being sent to the Anthropic Claude API for processing.' },
          { t: 'Acceptable Use', b: 'You agree not to: use the service for any unlawful purpose; attempt to access other users\u2019 data; reverse-engineer or attack the service; use automated scripts to abuse AI rate limits; or create multiple accounts to bypass trial limits.' },
          { t: 'Availability', b: 'AI Planner is provided as-is. We do not guarantee 100% uptime. AI features depend on third-party APIs (Google, Anthropic, Canvas, Stripe, Supabase) that may experience outages. During outages, the app falls back to cached data where possible.' },
          { t: 'Termination', b: 'You can delete your account at any time from Settings. We may suspend or terminate accounts that violate these terms or that fail payment after the trial ends.' },
          { t: 'Limitation of Liability', b: 'AI Planner is provided without warranty. We are not liable for missed deadlines, incorrect AI suggestions, or any academic or financial consequences resulting from reliance on the service. Our liability is capped at the fees you paid in the last 3 months.' },
          { t: 'Governing Law', b: 'These terms are governed by the laws of Victoria, Australia. Any disputes shall be resolved in the courts of Victoria, Australia.' },
          { t: 'Changes', b: 'We may update these terms. Material changes will be notified via email or in-app. Continued use after changes constitutes acceptance.' },
          { t: 'Contact', b: 'For any questions about these terms, email hello@mrgren.store.' },
        ].map((s) => (
          <div key={s.t} style={{ marginBottom: 24 }}>
            <h2 style={{ fontSize: 16, fontWeight: 600, color: T.text, marginBottom: 8 }}>{s.t}</h2>
            <p style={{ fontSize: 13, color: T.textSoft, lineHeight: 1.8, fontWeight: 300 }}>{s.b}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
