import { NextResponse } from 'next/server';
import { withAuth } from '@/lib/api-handler';
import { supabaseAdmin } from '@/lib/supabase';
import archiver from 'archiver';
import { Readable } from 'stream';

interface MaterialRow {
  id: string;
  course: string;
  week: number;
  source_file: string;
  content: Record<string, unknown>;
}

function generateHtml(course: string, week: number, sourceFile: string, content: Record<string, unknown>): string {
  const keyConcepts = (content.key_concepts as string[]) || [];
  const detailedNotes = (content.detailed_notes as string[]) || [];
  const pharmacyConnections = (content.pharmacy_connections as string[]) || [];
  const mcqs = (content.mcqs as { question: string; options: string[]; correct_answer: number; explanation: string }[]) || [];
  const flashcards = (content.flashcards as { term: string; definition: string }[]) || [];
  const examTraps = (content.exam_traps as string[]) || [];

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${course} - Week ${week} Study Materials</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; background: #060608; color: #e8e6e1; line-height: 1.7; padding: 24px; max-width: 800px; margin: 0 auto; }
  h1 { color: #0d9b8a; font-size: 24px; margin-bottom: 4px; }
  h2 { color: #0d9b8a; font-size: 18px; margin: 24px 0 12px; padding-bottom: 6px; border-bottom: 1px solid rgba(255,255,255,0.06); }
  h3 { color: #a09d95; font-size: 12px; font-weight: 400; margin-bottom: 20px; }
  .section { background: #0f0f14; border: 1px solid rgba(255,255,255,0.06); border-radius: 12px; padding: 18px; margin-bottom: 12px; }
  ul { padding-left: 20px; }
  li { margin-bottom: 6px; font-size: 14px; color: #a09d95; }
  .mcq { background: #131318; border: 1px solid rgba(255,255,255,0.06); border-radius: 8px; padding: 14px; margin-bottom: 10px; }
  .mcq-q { font-weight: 600; color: #e8e6e1; margin-bottom: 8px; font-size: 14px; }
  .mcq-opt { padding: 6px 12px; margin: 3px 0; border-radius: 6px; font-size: 13px; }
  .mcq-correct { background: rgba(61,165,93,0.12); border: 1px solid rgba(61,165,93,0.2); color: #3da55d; }
  .mcq-wrong { color: #5e5c56; }
  .mcq-exp { font-size: 12px; color: #a09d95; margin-top: 8px; font-style: italic; }
  .card { display: inline-block; width: calc(50% - 6px); vertical-align: top; background: #131318; border: 1px solid rgba(255,255,255,0.06); border-radius: 10px; padding: 14px; margin: 4px 3px; }
  .card-term { font-weight: 600; color: #0d9b8a; font-size: 13px; margin-bottom: 4px; }
  .card-def { font-size: 12px; color: #a09d95; }
  .trap { background: rgba(232,123,53,0.08); border-left: 3px solid #e87b35; border-radius: 0 8px 8px 0; padding: 8px 14px; margin-bottom: 6px; font-size: 13px; color: #e87b35; }
  .pharm { background: rgba(13,155,138,0.06); border-left: 3px solid #0d9b8a; border-radius: 0 8px 8px 0; padding: 8px 14px; margin-bottom: 6px; font-size: 13px; color: #0d9b8a; }
</style>
</head>
<body>
<h1>${course}</h1>
<h3>Week ${week} ${sourceFile ? `- ${sourceFile}` : ''} | AI-generated study materials</h3>

${keyConcepts.length > 0 ? `
<h2>Key Concepts</h2>
<div class="section">
<ul>${keyConcepts.map((c) => `<li>${c}</li>`).join('')}</ul>
</div>` : ''}

${detailedNotes.length > 0 ? `
<h2>Detailed Notes</h2>
<div class="section">
<ul>${detailedNotes.map((n) => `<li>${n}</li>`).join('')}</ul>
</div>` : ''}

${pharmacyConnections.length > 0 ? `
<h2>Pharmacy Connections</h2>
${pharmacyConnections.map((p) => `<div class="pharm">${p}</div>`).join('')}` : ''}

${mcqs.length > 0 ? `
<h2>Multiple Choice Questions</h2>
${mcqs.map((q, i) => `<div class="mcq">
<div class="mcq-q">${i + 1}. ${q.question}</div>
${q.options.map((o, j) => `<div class="mcq-opt ${j === q.correct_answer ? 'mcq-correct' : 'mcq-wrong'}">${String.fromCharCode(65 + j)}. ${o}${j === q.correct_answer ? ' \u2713' : ''}</div>`).join('')}
${q.explanation ? `<div class="mcq-exp">${q.explanation}</div>` : ''}
</div>`).join('')}` : ''}

${flashcards.length > 0 ? `
<h2>Flashcards</h2>
<div>${flashcards.map((f) => `<div class="card"><div class="card-term">${f.term}</div><div class="card-def">${f.definition}</div></div>`).join('')}</div>` : ''}

${examTraps.length > 0 ? `
<h2>Exam Traps</h2>
${examTraps.map((t) => `<div class="trap">${t}</div>`).join('')}` : ''}

<div style="margin-top: 32px; padding-top: 12px; border-top: 1px solid rgba(255,255,255,0.06); font-size: 11px; color: #5e5c56;">
Generated by AI Planner | ${new Date().toLocaleDateString('en-AU', { dateStyle: 'long' })}
</div>
</body>
</html>`;
}

export const GET = withAuth(async (req: Request, userId) => {
  const { searchParams } = new URL(req.url);
  const course = searchParams.get('course');
  const week = searchParams.get('week');
  const format = searchParams.get('format') || 'html';

  if (format === 'zip') {
    // Export all materials as ZIP
    let query = supabaseAdmin.from('materials').select('id, course, week, source_file, content').eq('user_id', userId).order('course').order('week');
    const { data: rows } = await query;

    if (!rows || rows.length === 0) {
      return NextResponse.json({ error: 'No materials to export' }, { status: 404 });
    }

    const archive = archiver('zip', { zlib: { level: 9 } });
    const chunks: Buffer[] = [];

    const readable = new Readable({
      read() {},
    });

    archive.pipe({
      write(chunk: Buffer) { chunks.push(chunk); return true; },
      end() { readable.push(null); },
      on() { return this; },
      once() { return this; },
      emit() { return true; },
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any);

    for (const row of rows as MaterialRow[]) {
      const content = row.content || {};
      const html = generateHtml(row.course, row.week, row.source_file, content);
      const filename = `${row.course.replace(/[^a-zA-Z0-9]/g, '_')}/Week_${row.week}_${row.source_file.replace(/[^a-zA-Z0-9.]/g, '_')}.html`;
      archive.append(html, { name: filename });
    }

    await archive.finalize();

    await new Promise<void>((resolve) => {
      archive.on('end', resolve);
    });

    const zipBuffer = Buffer.concat(chunks);

    return new NextResponse(zipBuffer, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': 'attachment; filename="study-materials.zip"',
      },
    });
  }

  // Single HTML export
  let query = supabaseAdmin.from('materials').select('id, course, week, source_file, content').eq('user_id', userId);

  if (course) query = query.eq('course', course);
  if (week) query = query.eq('week', parseInt(week));

  const { data: rows } = await query.order('course').order('week').limit(1);
  const row = rows?.[0] as MaterialRow | undefined;

  if (!row) {
    return NextResponse.json({ error: 'No materials found' }, { status: 404 });
  }

  const content = row.content || {};
  const html = generateHtml(row.course, row.week, row.source_file, content);

  return new NextResponse(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Disposition': `inline; filename="${row.course}_Week${row.week}.html"`,
    },
  });
});
